students/
  abc123 → { name: "Arjun", class: "8A", email: "parent1@gmail.com" }
  def456 → { name: "Meera", class: "8A", email: "parent2@gmail.com" }

attendance/
  2025-05-01/
    students/
      abc123 → { present: true }
      def456 → { present: false }
  2025-05-02/
    students/
      abc123 → { present: true }
      def456 → { present: true }

Subject: Monthly Absentee Report - 2025-05

Dear Admin,

Please find attached the absentee report for the month of 2025-05.

Summary:
Student ID: abc123 - Absentee Count: 5
Student ID: def456 - Absentee Count: 3
...

Kind regards,
Your Tuition Center Team

Subject: Monthly Absentee Report - May 2025

Dear Admin,

Please find attached the absentee report for the month of May 2025.

Absentee Report for May 2025:

| Student ID | Absentee Count |
|------------|----------------|
| abc123     | 5              |
| def456     | 3              |

Kind regards,
Your Tuition Center Team

services:
  - type: web
    name: attendance-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/firebase.json
      - key: FIREBASE_PROJECT_ID
        value: your-project-id
    secrets:
      - firebase.json

# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest || echo "Tests failed but continuing"

    # OPTIONAL: Deploy step
    # Uncomment and customize if you're deploying to a host
    # - name: Deploy to Render or another host
    #   run: ./deploy_script.sh

env:
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

on:
  schedule:
    - cron: '0 18 * * *'  # Every day at 18:00 UTC

# render.yaml
services:
  - type: web
    name: attendance-tracker-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

